spring.application.name=jobodia

#DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/jobodia
spring.datasource.username=postgres
spring.datasource.password=123

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#JWT
jwt.secret.key = CVb4AAnXuL45I9BwFmItZXMM0VHtT647sR7uitSWqtU

#MAIL
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a8a301001@smtp-brevo.com
spring.mail.password=xsmtpsib-83ea9f42b5726ed9f5a11f343719a03fe7a7828ac9a94553605b7dd0948e134e-bGrQ31gnF6m3mPhR                                         
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=honglylay14@gmail.com
